### ISSUE TITLE
How to generate the  Region-1 and Region-2 one-by-one?

### ISSUE THREAD

**Issue by ustc-hb** [chenchao666/Bone-Age-Assessment#1]
about the _Step 3: Generate the Heatmap for the Hand Reigon, Region-1 and Region-2 one-by-one_, I want to know:
How to generate the Heatmap for the Hand Reigon, Region-1 and Region-2 one-by-one?

**Comment by chenchao666** [comment]
> about the _Step 3: Generate the Heatmap for the Hand Reigon, Region-1 and Region-2 one-by-one_, I want to know:
> How to generate the Heatmap for the Hand Reigon, Region-1 and Region-2 one-by-one?

You can Generate the attention maps using main_classification.py. The core code of generate attention map is  GAPAttention()  in func_utils.py. You can generate different attention map one by one by feeding different input images in the model. Please check the details in our paper.

**Comment by Geroge-W** [comment]
@dlmaker-hb97 您好，请问您这个代码跑通了吗？可以交流一下吗？
