### ISSUE TITLE
Why the localization network is classification?

### ISSUE THREAD

**Issue by CongDo0820** [chenchao666/Bone-Age-Assessment#4]
As the title, I'm a bit confused about why the localization network is classification, why not regression? The final goal of the paper is regression, right? Can you explain it?
Many thanks.

**Comment by chenchao666** [comment]
The CAM-based localization method only work for classification task.

**Comment by chenchao666** [comment]
> As the title, I'm a bit confused about why the localization network is classification, why not regression? The final goal of the paper is regression, right? Can you explain it?
> Many thanks.

The CAM-based localization method only work for classification task.

**Comment by CongDo0820** [comment]
> > As the title, I'm a bit confused about why the localization network is classification, why not regression? The final goal of the paper is regression, right? Can you explain it?
> > Many thanks.
> 
> The CAM-based localization method only work for classification task.

Thanks for your reply.
